import * as THREE from 'three'
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js'
// import { Timer } from 'three'
import { Timer } from 'three/addons/misc/Timer.js'
import GUI from 'lil-gui'